"""The Current Hand (design handoff 07-E): fidelity to the prototype.

tests/data/currenthand_ref.json holds per-page digests generated by running
the handoff's own JavaScript (Navcher Page Studies.dc.html) under Node —
the Python port must reproduce every figure byte-for-byte, across seeds.
"""

import hashlib
import json
import os
import xml.etree.ElementTree as ET

import pytest

from odylang import currenthand as ch

REF = json.load(open(os.path.join(os.path.dirname(__file__), "data",
                                  "currenthand_ref.json")))
ORDER = ["record", "scrawl", "watch", "vigil", "disc"]


@pytest.mark.parametrize("seed", sorted(REF, key=int))
def test_pages_byte_exact_with_prototype(seed):
    figs = ch.studies(int(seed), 0.6)
    for pref, reg in zip(REF[seed], ORDER):
        f = figs[reg]
        md5 = hashlib.md5("|".join(e["d"] for e in f.elems).encode()).hexdigest()
        assert f.vb == pref["vb"], (seed, reg)
        assert len(f.elems) == pref["n"], (seed, reg)
        assert md5 == pref["md5"], (seed, reg)
        assert f.elems[0]["d"].startswith(pref["first"][:40]), (seed, reg)


def test_ribbon_is_a_closed_filled_path():
    d = ch.ribbon([[0, 88, 4], [50, 60, 8], [100, 88, 4]], 1.0)
    assert d.startswith("M") and d.endswith(" Z")


def test_mulberry32_determinism():
    a, b = ch.mul32(11 * 7919 + 13), ch.mul32(11 * 7919 + 13)
    assert [a() for _ in range(8)] == [b() for _ in range(8)]


def test_featural_devices_carried():
    # voicing = the released drop; the voiceless twin has none
    assert ch.HAND["b"].drop_at is not None and ch.HAND["p"].drop_at is None
    assert ch.HAND["d"].drop_at is not None and ch.HAND["t"].drop_at is None
    # h: the ink runs dry — two pen strokes with a gap
    assert len(ch.HAND["h"].pen) == 2
    # T• is the filled eye (accent channel), =zu the only straight uniform
    # stroke (accent channel, two points, constant width)
    assert ch.HAND["mTs"].pen_acc2 and not ch.HAND["mTs"].pen
    azu = ch.HAND["azu"].pen_acc[0]
    assert len(azu) == 2 and azu[0][2] == azu[1][2]
    # the gap is written in subdued ink, split around a silence
    assert len(ch.HAND["gap"].pen_sub) == 2


def test_token_adapter_matches_navcher_tokens():
    assert ch.keys_from_tokens(["v", "e", "r", "@T", "=ka"]) == \
        ["v", "e", "r", "mT", "aka"]
    assert ch.keys_from_tokens(["|"]) == ["gap"]
    assert ch.keys_from_tokens(["u:", "?"]) == ["u:", "q"]


def test_line_svg_renders_phrasebook_line():
    from odylang.cli import _sentence_tokens
    from odylang.phrasebook import line
    tokens = _sentence_tokens(line(40).sentence, "bridge")
    svg = ch.line_svg(tokens)
    root = ET.fromstring(svg)
    assert root.tag.endswith("svg")
    assert len(root.findall(".//{http://www.w3.org/2000/svg}path")) > 10


@pytest.mark.parametrize("register", ORDER)
def test_page_svg_valid(register):
    svg = ch.page_svg(register, seed=11)
    root = ET.fromstring(svg)
    assert root.tag.endswith("svg")


def test_specimen_weaves_attested_words():
    """The design: 'every attested word woven in' — the fixed W words
    appear in the careful-hand stream regardless of seed."""
    sents = ch._make_sents(ch.mul32(42 * 7919 + 13))
    stream = []
    for line_keys in ch._flow(sents, "careful", 1e9):
        stream.extend(line_keys)
    joined = "|".join(stream)
    for w in (ch.W["enmai"], ch.W["zukad"], ch.W["jel"], ch.W["suchel"],
              ch.W["holt"]):
        assert "|".join(w) in joined


def test_logos_hand_is_faceted_not_curved():
    """The Logos hand shares the Current Hand's skeleton but renders straight
    facets (linear) instead of Catmull-Rom curves — a different SVG path for
    the same tokens."""
    from odylang import navcher
    toks = navcher.tokens_careful("sūchel jel")
    current = ch.line_svg(toks)
    logos = ch.logos_line_svg(toks)
    assert current != logos
    assert logos.startswith("<svg") and logos.rstrip().endswith("</svg>")
    # squared ribbons carry fewer vertices than the 8x-upsampled smooth ones
    assert logos.count(" L") < current.count(" L")


def test_logos_is_deterministic():
    from odylang import navcher
    toks = navcher.tokens_careful("enmai ver ish-ol")
    assert ch.logos_line_svg(toks) == ch.logos_line_svg(toks)


def test_ribbon_squared_differs():
    pts = [[0, 88, 4], [30, 50, 9], [60, 90, 5], [100, 88, 4]]
    assert ch.ribbon(pts, 1.0, squared=False) != ch.ribbon(pts, 1.0, squared=True)


def test_studies_unchanged_by_squared_default():
    """The five page studies still render with the smooth (curved) ribbon —
    the byte-lock against the prototype must not regress."""
    figs = ch.studies(11, 0.6)
    # a spot check: the record page still produces the same element count as
    # the reference fixture (full byte-lock is test_pages_byte_exact_...)
    assert len(figs["record"].elems) == REF["11"][0]["n"]
